"""
JalRakshak — Python Hydraulic Prototype Engine (Non-HEC-RAS Prototype)
======================================================================
CLASSIFICATION: PYTHON HYDRAULIC PROTOTYPE (SYNTHETIC ALGORITHMIC CROSS-CHECK)
NOT A NATIVE HEC-RAS EXECUTION — NOT GENERATED BY RasUnsteady.exe

Purpose:
1. Algorithmic cross-check and testing of Python shallow water routing logic.
2. Ingestion adapter schema verification for software regression testing.
3. Development debugging.

Governing Rule:
This code is NOT a physics authority, is NOT a calibrated simulation,
and must NEVER be represented as a native HEC-RAS 7.0.1 calculation.
"""

import os
import sys
import hashlib
import datetime
import numpy as np
import rasterio
import h5py
from pyproj import Transformer

def run_python_hydraulic_prototype():
    print("=================================================================")
    print("  PYTHON HYDRAULIC PROTOTYPE (SYNTHETIC ALGORITHMIC ENGINE)      ")
    print("  CLASSIFICATION: SYNTHETIC / NON-HEC-RAS PROTOTYPE              ")
    print("=================================================================")

    dem_path = os.path.join("data", "tehri", "derived", "tehri_pilot_utm44n_25m.tif")
    if not os.path.exists(dem_path):
        raise FileNotFoundError(f"Derived DEM not found at {dem_path}")

    with rasterio.open(dem_path) as src:
        dem = src.read(1)
        transform = src.transform
        bounds = src.bounds
        res_x = transform[0]
        res_y = abs(transform[4])
        nrows, ncols = dem.shape

    print(f"[Phase 1] Loaded DEM: {ncols} x {nrows} cells @ {res_x:.1f}m resolution (UTM 44N)")

    # 1. Define 2D Computational Flow Area (Tehri Gorge ~15 km reach)
    trans = Transformer.from_crs("EPSG:4326", "EPSG:32644", always_xy=True)
    dam_x, dam_y = trans.transform(78.4803, 30.3780)
    dam_row = int((bounds.top - dam_y) / res_y)
    dam_col = int((dam_x - bounds.left) / res_x)

    print(f"[Phase 2] Dam Point in Mesh: X={dam_x:.1f}, Y={dam_y:.1f}, Row={dam_row}, Col={dam_col}")

    # Build 2D Mesh Cells along the 15km Bhagirathi canyon (Row 100 to 680, valley elevation <= 850m)
    cell_coords = []
    cell_elevs = []
    cell_grid_idx = []

    for r in range(100, 680):
        for c in range(50, 380):
            z = dem[r, c]
            if z <= 850.0:  # Inundation envelope in canyon
                x = bounds.left + (c + 0.5) * res_x
                y = bounds.top - (r + 0.5) * res_y
                cell_coords.append([x, y])
                cell_elevs.append(z)
                cell_grid_idx.append((r, c))

    cell_coords = np.array(cell_coords, dtype=np.float64)
    cell_elevs = np.array(cell_elevs, dtype=np.float32)
    n_cells = len(cell_coords)
    print(f"[Phase 3] Constructed 2D Prototype Mesh: {n_cells} cells")

    # 2. Time parameters
    duration_hrs = 12.0  # 12-hour prototype simulation
    output_interval_min = 10.0  # 10-minute output intervals
    n_steps = int(duration_hrs * 60 / output_interval_min) + 1  # 73 time steps
    times_hrs = np.linspace(0.0, duration_hrs, n_steps)

    start_date = datetime.datetime(2026, 9, 24, 0, 0, 0, tzinfo=datetime.timezone.utc)
    time_date_stamps = []
    for t_h in times_hrs:
        dt = start_date + datetime.timedelta(hours=t_h)
        stamp = dt.strftime("%d%b%Y %H:%M:%S").upper()
        time_date_stamps.append(stamp.encode("ascii"))
    time_date_stamps = np.array(time_date_stamps, dtype="|S19")

    # 3. Dynamic Froehlich (2008) Breach Hydrograph Mechanics
    print("[Phase 4] Computing Froehlich (2008) Dynamic Breach Outflow Hydrograph...")
    
    tf_hrs = 2.4
    Bb = 215.0
    Z = 0.7
    Z_invert = 600.0
    initial_wse = 830.0
    Cw = 1.70
    
    current_wse = initial_wse
    dt_sec = 60.0  # 1-minute internal integration
    total_steps_int = int(duration_hrs * 3600 / dt_sec)
    
    internal_times = []
    internal_Q = []
    internal_WSE = []
    cum_volume_out = 0.0

    for step in range(total_steps_int + 1):
        t_sec = step * dt_sec
        t_h = t_sec / 3600.0
        
        if t_h <= 0.5:
            frac = t_h / 0.5
            curr_Bb = 10.0 + (Bb - 10.0) * 0.05 * frac
            curr_invert = 830.0 - (830.0 - 750.0) * frac
        elif t_h <= tf_hrs:
            frac = (t_h - 0.5) / (tf_hrs - 0.5)
            curr_Bb = 10.0 + (Bb - 10.0) * (0.05 + 0.95 * frac)
            curr_invert = 750.0 - (750.0 - Z_invert) * frac
        else:
            curr_Bb = Bb
            curr_invert = Z_invert
            
        head = max(0.0, current_wse - curr_invert)
        if head > 0:
            Q_rect = Cw * curr_Bb * (head ** 1.5)
            Q_tri = (4.0 / 15.0) * np.sqrt(2.0 * 9.81) * Z * (head ** 2.5) * 0.6
            Q_tot = Q_rect + Q_tri + 180.0
        else:
            Q_tot = 180.0
            
        h_ratio = max(0.0, min(1.0, (current_wse - 600.0) / 230.0))
        area_res = (12.0 + 30.0 * h_ratio) * 1e6  # m2
        
        dWSE = (Q_tot * dt_sec) / area_res
        current_wse = max(600.0, current_wse - dWSE)
        cum_volume_out += Q_tot * dt_sec
        
        internal_times.append(t_h)
        internal_Q.append(Q_tot)
        internal_WSE.append(current_wse)

    # 4. Hydrodynamic 2D Routing down the 15 km Canyon Mesh
    print("[Phase 5] Solving 2D Hydrodynamic Flood Wave Propagation on Mesh...")
    
    dists_downstream = []
    for pt in cell_coords:
        dy = max(0.0, dam_y - pt[1])
        dx = abs(pt[0] - dam_x)
        d_val = np.sqrt(dx**2 + dy**2) * 1.25
        dists_downstream.append(d_val)
    dists_downstream = np.array(dists_downstream)

    wse_array = np.zeros((n_steps, n_cells), dtype=np.float32)
    vel_array = np.zeros((n_steps, n_cells * 2), dtype=np.float32)

    manning_n = 0.045
    s0 = 0.004

    for t_idx, t_h in enumerate(times_hrs):
        int_idx = int(t_h * 3600 / dt_sec)
        int_idx = min(len(internal_Q) - 1, int_idx)
        
        q_dam = internal_Q[int_idx]
        wse_res = internal_WSE[int_idx]
        
        for c_idx in range(n_cells):
            z_bed = cell_elevs[c_idx]
            d_val = dists_downstream[c_idx]
            
            if cell_coords[c_idx, 1] >= dam_y - 200.0:
                wse_val = max(z_bed, wse_res)
                v_val = 0.5
            else:
                travel_time_hrs = d_val / (14.0 * 3600.0)
                if t_h >= travel_time_hrs:
                    int_local_idx = int((t_h - travel_time_hrs) * 3600 / dt_sec)
                    int_local_idx = max(0, min(len(internal_Q) - 1, int_local_idx))
                    
                    atten_factor = np.exp(-0.000025 * d_val)
                    q_local = internal_Q[int_local_idx] * atten_factor
                    
                    canyon_width = 40.0 + 0.002 * d_val
                    depth = (q_local * manning_n / (canyon_width * np.sqrt(s0))) ** 0.6
                    
                    valley_invert = 617.5 - (d_val / 15000.0) * (617.5 - 540.0)
                    local_wse = valley_invert + depth
                    
                    if local_wse > z_bed:
                        wse_val = local_wse
                        v_val = min(18.0, max(1.0, q_local / (canyon_width * max(0.5, local_wse - z_bed))))
                    else:
                        wse_val = z_bed
                        v_val = 0.0
                else:
                    base_depth = (180.0 * manning_n / (40.0 * np.sqrt(s0))) ** 0.6
                    valley_invert = 617.5 - (d_val / 15000.0) * (617.5 - 540.0)
                    base_wse = valley_invert + base_depth
                    if base_wse > z_bed:
                        wse_val = base_wse
                        v_val = 2.5
                    else:
                        wse_val = z_bed
                        v_val = 0.0
                        
            wse_array[t_idx, c_idx] = wse_val
            vel_array[t_idx, c_idx] = v_val
            vel_array[t_idx, n_cells + c_idx] = v_val * 0.95

    # 5. Write to Synthetic Prototype Directory
    out_dir = os.path.join("artifacts", "hecras", "synthetic")
    os.makedirs(out_dir, exist_ok=True)
    out_hdf = os.path.join(out_dir, "tehri_python_hydraulic_prototype.hdf")

    print(f"[Phase 6] Exporting Python Prototype HDF5: {out_hdf}...")
    
    with h5py.File(out_hdf, "w") as h5:
        h5.attrs["File Type"] = "HEC-RAS Results (Python Prototype Simulation)"
        h5.attrs["File Version"] = "Python Hydraulic Prototype v1.0"
        h5.attrs["Projection"] = 'PROJCS["WGS_1984_UTM_Zone_44N",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",81.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]'
        h5.attrs["Units System"] = "SI Units"
        h5.attrs["Simulation Source"] = "PYTHON_HYDRAULIC_PROTOTYPE"

        plan_grp = h5.create_group("Plan Data/Plan Information")
        plan_grp.attrs["Plan Title"] = "Tehri Pilot 2D Python Prototype"
        plan_grp.attrs["Plan ShortID"] = "TehriPythonProto"
        plan_grp.attrs["Project Title"] = "Tehri Python Prototype Study (Synthetic Cross-Check)"
        plan_grp.attrs["Units System"] = "SI Units"
        plan_grp.attrs["Simulation Start Time"] = "24Sep2026 00:00:00"
        plan_grp.attrs["Simulation End Time"] = "24Sep2026 12:00:00"
        plan_grp.attrs["Base Output Interval"] = "10MIN"
        plan_grp.attrs["Computation Time Step Base"] = "1SEC"

        geom_base = "Geometry/2D Flow Areas/TehriCanyon"
        h5.create_dataset(f"{geom_base}/Cells Center Coordinate", data=cell_coords, dtype="float64")
        h5.create_dataset(f"{geom_base}/Cells Minimum Elevation", data=cell_elevs, dtype="float32")

        res_base = "Results/Unsteady/Output/Output Blocks/Base Output/Unsteady Time Series"
        h5.create_dataset(f"{res_base}/Time Date Stamp", data=time_date_stamps, dtype="|S19")
        h5.create_dataset(f"{res_base}/Time", data=times_hrs, dtype="float64")
        h5.create_dataset(f"{res_base}/Time Step", data=np.full(n_steps, 600.0, dtype=np.float32), dtype="float32")

        fa_res = f"{res_base}/2D Flow Areas/TehriCanyon"
        h5.create_dataset(f"{fa_res}/Water Surface", data=wse_array, dtype="float32")
        h5.create_dataset(f"{fa_res}/Face Velocity", data=vel_array, dtype="float32")

    sz = os.path.getsize(out_hdf)
    with open(out_hdf, "rb") as f:
        sha256 = hashlib.sha256(f.read()).hexdigest()

    print("=================================================================")
    print("  PYTHON HYDRAULIC PROTOTYPE EXPORT COMPLETED                    ")
    print("=================================================================")
    print(f"Output HDF5: {out_hdf}")
    print(f"File Size: {sz:,} bytes")
    print(f"SHA-256: {sha256}")
    print("=================================================================")

    return out_hdf, sha256

if __name__ == "__main__":
    run_python_hydraulic_prototype()
